const CONFIG = {
    titleWeb: "Hé lu anh iu",
    introTitle: 'Đây là một bài kiểm tra 15p',
    introDesc: `Đọc password để đăng nhập vào chái tym của Lan`,
    btnIntro: 'Uki',
    title: 'Anh có thấy Lan đáng iu hum🥰',
    desc: 'Lan là ngừi cute nhất trên đời đúng hum ạ?',
    btnYes: 'Đúng gòi',
    btnNo: 'Khum nha :3 anh đáng iu hơn',
    question: 'Trên thế giới hơn 7 tỉ người, nụ cười của ... là xinh đẹp nhất (điền vào chỗ trống)',
    btnReply: 'Lan',
    reply: 'Cũng là Lan luôn',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Tối nay đi trì khum',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/lancute2trieunam/',
}
